### ISSUE TITLE
Error when I try to npm run scrape

### ISSUE THREAD

**Issue by No1ceTea** [Gobluebro/Geekhack-scraper#26]
Hello ! 

I create a clone of the project on my machine and I don't know why it's doesn't work, I got these error : 

Geekhack-scraper\node_modules\sequelize\src\sequelize.js:193
      options.dialect = urlParts.protocol.replace(/:$/, '');
                                          ^
TypeError: Cannot read properties of null (reading 'replace')
    at new Sequelize (C:\Users\thaiw\Desktop\Github\Geekhack-scraper\node_modules\sequelize\src\sequelize.js:193:43)
    at Object.<anonymous> (C:\Users\thaiw\Desktop\Github\Geekhack-scraper\database\initdb.ts:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (C:\Users\thaiw\Desktop\Github\Geekhack-scraper\node_modules\ts-node\src\index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\thaiw\Desktop\Github\Geekhack-scraper\node_modules\ts-node\src\index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    
   If you can help me to try to solve this 
   
   Thanks a lot for your work !

**Comment by Gobluebro** [comment]
Have you set up your database and entered the credentials into your `.env` file?

**Comment by Gobluebro** [comment]
Gonna close for inactivity
